### ISSUE TITLE
Bug: Indent with inline css styles

### ISSUE THREAD

**Issue by what1s1ove** [prettier/plugin-pug#262]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v1.16.1                  |
| Prettier  | v2.3.1                  |
| Framework | none |
| Node      | v14.17.3                  |
| OS        | mac           |

## Prettier config

```yml
tabWidth: 4
bracketSpacing: true
printWidth: 120
singleQuote: true
trailingComma: none
useTabs: true
semi: true
arrowParens: avoid
endOfLine: auto
overrides:
  - files: '*.pug'
    options:
      pugTabWidth: 4
      pugUseTabs: 'true'
      pugSingleQuote: 'true'
      pugAttributeSeparator: always
      pugClosingBracketPosition: new-line
      pugWrapAttributesThreshold: 1
      pugExplicitDiv: false
      pugClassNotation: literal
      pugEmptyAttributes: none
      pugSortAttributes: asc
      pugSortAttributesBeginning:
        - id
        - class
        - src
        - href
        - type
        - width
        - height
        - alt
        - aria-
        - data-
```

## Input

```pug
html
	head
		style(type='text/css').
			.container {
			  background-color: #e8eff3;
			  padding: 40px;
			  font-size: 1.1rem;
			}
```

## Expected Output

```pug
html
	head
		style(type='text/css').
			.container {
				background-color: #e8eff3;
				padding: 40px;
				font-size: 1.1rem;
			}
```

## Additional Context

Hi there!

after prettify
![image](https://user-images.githubusercontent.com/42296182/127437246-220c331b-360f-4c6f-a089-b008888b1e88.png)

but should be like
![image](https://user-images.githubusercontent.com/42296182/127437321-1b6f5d85-9569-48d9-9c4f-e473c516fcb1.png)

Also, I use `editorconfig-checker` so I can't do anything at all 😥
![image](https://user-images.githubusercontent.com/42296182/127437379-1863beee-2994-4695-af20-4cc459928d5f.png)

Can you please tell me what is better for me to do? 🙏
